# Generated by Django 4.2.18 on 2025-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation_time', models.TextField()),
                ('description', models.TextField()),
                ('ingredients', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('BF', 'Breakfast'), ('LN', 'Lunch'), ('DI', 'Dinner'), ('DE', 'Desserts')], max_length=2)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product')),
            ],
        ),
    ]
