# Generated by Django 4.2.18 on 2025-02-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipeapp', '0004_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='tracking_no',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
