# Generated by Django 4.2.18 on 2025-02-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipeapp', '0005_orderplaced_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='tracking_no',
        ),
    ]
