# Generated by Django 4.2.18 on 2025-02-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipeapp', '0006_remove_orderplaced_tracking_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
