# Generated by Django 4.2.18 on 2025-02-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipeapp', '0009_orderplaced_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
