# Generated by Django 4.2.18 on 2025-02-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipeapp', '0011_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
