# Generated by Django 4.2.18 on 2025-02-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipeapp', '0013_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
