# Generated by Django 4.2.18 on 2025-02-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipeapp', '0016_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
